version: '2'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    volumes:
      - ./web/:/usr/src/app/web
    command: flask run --host=0.0.0.0

  postgres:
    ports:
      - "5432:5432"
